### ISSUE TITLE
add EventClick

### ISSUE THREAD

**Issue by BenArfanour** [fados-produccions/fullCalendarBundle#1]
Acually it works for me but i'm gonaa ask you somthing 
i wouloud  add EventClik which i can get more information from my databsae !  how ?

**Comment by albertjuhe** [comment]
Hi,

I've update the Bundle, the file init.fullCalendar.js has been updated, this file is where you cant find the EventClick manager. If you want to overwrite this file, becouse you want to change this event action, simply copy this file outside the js/bundle and modify the fullcalendar url resource twigs.

For example:
change this line <script type="text/javascript" src="{{ asset('bundles/fullcalendar/js/init.fullCalendar.js') }}"></script> for this <script type="text/javascript" src="{{ asset('js/init.fullCalendar.js') }}"></script>, and copy the init.fullCalendar.js to web/js folder.

best regards,

**Comment by BenArfanour** [comment]
What u mean u are update the bundle should i install it again or what , cause i got the same errors after change the file into web/js and change url ressource twigs ,

**Comment by BenArfanour** [comment]
what u mean : event click manger  i guess there is a function missed here about event click here  no ??
`<?php

/**
 * Created by PhpStorm.
 * User: Albert
 * Date: 23/2/2016
 * Time: 8:52
 */
namespace fadosProduccions\fullCalendarBundle\Services;

use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Component\DependencyInjection\ContainerInterface as Container;
use Doctrine\ORM\EntityManager;

class CalendarManagerRegistry
{
    protected $managerRegistry;
    protected $container;
    protected $recipient;
    protected $manager;

    public function __construct(ManagerRegistry $managerRegistry, Container $container)
    {
        $this->container = $container;
        $this->recipient = $this->container->getParameter( 'class_manager' );
        $this->managerRegistry = $managerRegistry;
        $this->manager = $this->managerRegistry->getManagerForClass($this->recipient);

    }

    public function getManager() {
        return $this->manager;
    }

    public function getEvents($dataFrom,$dataTo) {
        $qb = $this->manager->createQueryBuilder()
            ->select('c')
            ->from($this->recipient, 'c')
            ->where('c.startDatetime BETWEEN :firstDate AND :lastDate')
            ->setParameter('firstDate', $dataFrom)
            ->setParameter('lastDate', $dataTo)
        ;

        return $qb->getQuery()->getResult();


    }

    public function changeDate($newStartData,$newEndData,$id) {
        $entity = $this->manager->getRepository($this->recipient)->find($id);
        $entity->setStartDatetime(new \DateTime($newStartData));
        $entity->setEndDatetime(new \DateTime($newEndData));
        $this->save($entity);
   }

    public function resizeEvent($newDate,$id) {
        $entity = $this->manager->getRepository($this->recipient)->find($id);
        $entity->setEndDatetime(new \DateTime($newDate));
        $this->save($entity);
   }

    public function serialize($elements) {
        $result = [];
        foreach ($elements as $element) {
            $result[] = $element->toArray();
        }
        return json_encode($result);
    }

    public function save($entity) {
        $this->manager->persist($entity);
        $this->manager->flush();
    }


}`

**Comment by BenArfanour** [comment]
hhhhh thanks bro it works now for me after 2 days of searching >.< I've got a war in my mind

**Comment by albertjuhe** [comment]
Perfect!!!!

Best regards,
Albert
